include:
  - project: 'uniprot/front-end/front-end-deploy'
    file: 'templates/.gitlab-ci-template.yml'

variables:
  CHART_PROD: 'quickgofe-prod'
  CHART_FALLBACK: 'quickgofe-fallback'

stages:
  - build_static_assets
  - build_docker_image
  - deploy

build_static_assets:
  only:
    refs:
      - main
  stage: build_static_assets
  image: starefossen/ruby-node
  script:
    - git --version
    - node --version
    - npm --version
    - ruby --version
    - gem install compass
    - npm install -g grunt-cli bower
    - npm install
    - bower install
    - grunt build
    - mv dist build
  artifacts:
    paths:
      - build/