include:
  - project: 'uniprot/front-end/front-end-deploy'
    file: '.gitlab-ci-template.yml'

variables:
  CHART_PROD: 'quickgofe-prod'
  CHART_FALLBACK: 'quickgofe-fallback'
  CHART_DEV: 'quickgofe-dev'

.ruby_node:
  image: ${DOCKER_IMAGES_REPO}/ruby-node:${DOCKER_IMAGES_VERSION}
  before_script:
    - git --version
    - node --version
    - npm --version
    - ruby --version
    - npm install
    - bower install

test:
  extends: .ruby_node
  script:
    - grunt test

merge_and_test:
  only:
    - external_pull_requests
  extends: .ruby_node
  stage: test
  script:
    - echo Merging $CI_COMMIT_SHORT_SHA into $CI_EXTERNAL_PULL_REQUEST_TARGET_BRANCH_NAME to test upstream effects
    - git config --global user.email "uniprotci@gmail.com"
    - git config --global user.name "UniProt CI"
    - git fetch origin $CI_EXTERNAL_PULL_REQUEST_TARGET_BRANCH_NAME
    - git checkout $CI_EXTERNAL_PULL_REQUEST_TARGET_BRANCH_NAME
    - git reset --hard origin/$CI_EXTERNAL_PULL_REQUEST_TARGET_BRANCH_NAME
    - git merge $CI_COMMIT_SHA --no-ff -m "Merge and test"
    - test -n "$(git status --porcelain)" && exit 1 # Exit if merge has conflicts
    - grunt test

build_static_assets:
  extends: .ruby_node
  script:
    - grunt build:dev
    - mv dist build
