language: node_js
node_js:
  - '4.1'
before_script:
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - 'npm install bower grunt-cli -g'
  - 'npm install'
  - 'bower install'
  - 'gem install compass'
script:
  - 'npm run test'
notifications:
  slack: quickgo:1Nu7WlcecKOsojoVtjvw9Lx3
